### ISSUE TITLE
Update yamlpp-* tools to support the Merge feature.

### ISSUE THREAD

**Issue by ArcticSnowman** [perlpunk/YAML-PP-p5#35]
The utilities shipped with YAML do not support https://metacpan.org/pod/YAML::PP::Schema::Merge feature.

It's be really nice if they had it turned on by default or via some command line flag.

@perlpunk Kudos on being one of the first PERL YAML parsers to support this feature. 

Thanks

**Comment by perlpunk** [comment]
Indeed, I want to add more options to the several utilities.

**Comment by perlpunk** [comment]
I released 0.023_001.
`yamlpp-load` and `yamlpp-load-dump` now have new options `--merge` and `--module`.
Maybe you can try it out?

**Comment by perlpunk** [comment]
I released 0.024
