### ISSUE TITLE
ypp fails to parse !~

### ISSUE THREAD

**Issue by ingydotnet** [perlpunk/YAML-PP-p5#47]
https://play.yaml.io/main/parser?input=LSAhfiBmb28K

**Comment by perlpunk** [comment]
That has already been fixed in version 0.32

**Comment by ingydotnet** [comment]
Oops. I need to update the playground engine.

**Comment by ingydotnet** [comment]
https://play.yaml.io/main/parser?input=LSAhfiBmb28K working now with 0.034
